FROM python:3.8

WORKDIR /

ENV FILE=sql_server_fixed.py

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install requests
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev

COPY . .

ENTRYPOINT python ${FILE} ${PORT} --database "sqlite:///data.db"

